[package]
name = "pngchat"
version = "0.1.0"
edition = "2021"
description = "Encrypted communication using PNG images"
authors = ["Azathoth"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
