on: [push, pull_request]

name: Lints and checks

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Format
        run: cargo fmt --check
